### ISSUE TITLE
Error on code activation (dw_api_activate_code): ERR_TLS_CERT_ALTNAME_INVALID

### ISSUE THREAD

**Issue by C-Lacerda** [SalesforceCommerceCloud/sfcc-ci#199] opened 2021-02-04 17:58 UTC
Hi, we did the p12 file as usual, the code is uploading, also metadata, but on the activation code step we receive an error:
**dw_activate.js --> dw_api_activate_code.js**
...let codeApi = require('sfcc-ci').code;
codeApi.activate(options.baseUrl, options.version, token, function (error) {...

baseUrl, version and token are correct
From the console logs that we put on it function we can see just this error:
**ERR_TLS_CERT_ALTNAME_INVALID**
![image](https://user-images.githubusercontent.com/74203210/106934830-5ee6b580-66f9-11eb-8d77-b7208fb67e25.png)

**Comment by C-Lacerda** [comment] 2021-02-18 20:26
@tobiaslohr  could you please give us a help with: ERR_TLS_CERT_ALTNAME_INVALID at activation code step?

**Comment by tobiaslohr** [comment] 2021-05-26 20:58
@C-Lacerda This error is coming from the build-suite right? Didn't you use a stable version of sfcc-ci in the build-suite?

@dmersiowsky FYI

**Comment by dmersiowsky** [comment] 2021-05-27 07:34
The error indicates an issue with the SSL Certificate used for the Server you are calling.
You can try if `npm config set strict-ssl false` fixes the issue.

Would be good to know the Hostname and the underlying SSL Certificate setup, not sure if you want to share it here though.

However, it is most likely an SSL issue and not a bug in Build Suite or sfcc-ci.

"baseURL" - you are not running the activation call against the "cert.*" URL, right?

**Comment by tobiaslohr** [comment] 2022-01-24 13:05
@C-Lacerda Is this issue resolved, did you follow the suggestion made and can we close it?

**Comment by C-Lacerda** [comment] 2022-01-24 19:10
Yes, it was a wrong staging URL.


Cassio Lacerda | ArganoUV

Digital Architect

+55 (51) 99223-7223 | weareuv.com<https://weareuv.com/>

***@***.*** | LinkedIn<https://www.linkedin.com/company/wearearganouv/>

We are Argano<https://www.argano.com/>

We build the Digital Foundations that make businesses run better
________________________________

**Comment by tobiaslohr** [comment] 2022-01-25 11:25
thanks @C-Lacerda

**Closed by tobiaslohr** 2022-01-25 11:25 UTC
Labels: help wanted
