### ISSUE TITLE
Issues while listing and creating SFCC Users Through sfcc -ci 

### ISSUE THREAD

**Issue by ngaddipati33** [SalesforceCommerceCloud/sfcc-ci#164] opened 2020-06-24 18:33 UTC
Issues while trying to list and create Users Through API 

Any help on this would be very useful

./sfcc-ci-macos org:list - This is working fine

**Listing Users failing**
 
1) List of users in Account Manager (in org not in instance) seems to fail:
$ ./sfcc-ci-macos user:list --org (Org Id XXX)

**Error: Authentication invalid. Please (re-)authenticate by running ´sfcc-ci auth:login´ or ´sfcc-ci client:auth´**

2) $ ./sfcc-ci-macos user:list --org "(Org Name)"

**Error: Authentication invalid. Please (re-)authenticate by running ´sfcc-ci auth:login´ or ´sfcc-ci client:auth´**

**User Creation failing:**

1)  User Create in Account Manager seems to fail:
$ ./sfcc-ci-macos user:create --org "(Org Id)" --login Email id(xxx@xx.com) --user '{"email": "XXXXXX", "first_name": "XXXXX", "last_name": "XX, "roles": ["xchange-user"]}'

**Error: Authentication invalid. Please (re-)authenticate by running ´sfcc-ci auth:login´ or ´sfcc-ci client:auth´**

Any help on this would be very helpful. Thanks in advance

**Comment by taehyunlim** [comment] 2020-06-25 22:21
Expired auth tokens cause validation to fail. As the error message suggests, you will need to re-authenticate by running `sfcc-ci auth:login` or `sfcc-ci client:auth` depending on your auth method.

**Comment by sftschaerff** [comment] 2020-06-26 10:05
Hi @ngaddipati33,

as written by taehyunlim, please try to re-authenticate first and then run `sfcc-ci user:list`. 

Best regards
Tobias

**Comment by Makayez** [comment] 2020-07-01 03:47
It doesn't seem to be a expired auth as I can continue getting a user list - just user:create at the Account Manager / Org level seems to trigger the message.  I can add at the instance level too.

**Comment by sftschaerff** [comment] 2020-07-02 09:28
Hi @Makayez,

to get a deeper understanding of the problem, I need more informations. Please answer the following questions:
- What authentication method have you used `sfcc-ci client:auth` or `sfcc-ci auth:login` ?
- In Account Manager do you have the permissions to create a user in the org or in the instance?

Thank you and Best regards
Tobias

**Comment by walter-foulkes** [comment] 2020-07-21 23:06
I have this same issue using client:auth

**Comment by sftschaerff** [comment] 2020-07-22 07:18
Hi @walter-foulkes,

can you please try to use the command
`sfcc-ci user:list --org xxxxxxxxxxxxxxxxxxxxxxx`

What is the result here?
Please keep in mind to use the exact same ID, which got returned from the command
`sfcc-ci org:list xxxxxxxxxxxxxxxxxxxxxxx`.

Best regards
Tobias

**Comment by walter-foulkes** [comment] 2020-07-22 15:16
I did try this.

Thanks,
Walter Foulkes

Senior Systems Engineer
DCPI Shared Services
1200 N Grand Central Avenue
Glendale, CA 91201-2426
E-mail: walter.foulkes@disney.com<mailto:walter.foulkes@disney.com>
W 818.931.2342 | M 817.917.9563

**Comment by walter-foulkes** [comment] 2020-07-23 19:16
is there any traction on this issue?

**Comment by sftschaerff** [comment] 2020-07-24 07:34
Hi @walter-foulkes,

I'm currently clarifying the issue and I will let you know here, once I have an answer.

Regards
Tobias

**Comment by sftschaerff** [comment] 2020-07-24 08:01
Hi @walter-foulkes,

does your account manager user have the role "account admin"? You need this role to perform user-related actions in account manager.

Regards
Tobias

**Comment by walter-foulkes** [comment] 2020-07-29 00:01
I would like to take the time to post what I found to get past this issue. 
1. you need the API configured along with your user... these are completely sepererate but both required for the dw.json to auth properly to the org. Also if you have multiple instance leave out the hostname. 
{
    "client-id": "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
    "client-secret": "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
    "username": "user",
    "password": "password"
}

2. I found the TenantFIlters for the ream by looking at my users config and just testing what I found. This was a little difficult to understand. 

Below is my script that will configure the user for the org and then assign them to the roles the need for the different instances.  Here are the steps to set it up. 
####Create a file on your desktop with all the users you want to add and their roles named <NEW_USERS>
FORMAT: (you can have as many Roles as you need)
name@emailaddress.com FirstName LastName Role Role Role Role

EXAMPLE FILE:
walt.doe@mycomp.com Walt Doe bm-admin logcenter-user bm-user
john.doe@mycomp.com John Doe bm-user om-user 
jane.doe@mycomp.com Jane Doe om-user 

ENVIRONMENT:
This is your TenantFilter = <realm_instance> 

SCRIPT:
source ~/.bash_profile
ORG=$(sfcc-ci org:list --json |jq -r  '.[]' |jq -r '.name')
length=$(awk '{ print NF}' NEW_USERS | awk -F' ' -v max=0 '{if($1>max){content=$0; max=$1}}END{print content}')

cd $WORKSPACE
sfcc-ci client:auth
echo "#### CREATING USERS AT THE ORG LEVEL"
cat NEW_USERS|awk '{print $1, $2, $3, $4}' | while read email first last role; do sfcc-ci user:create --org "$ORG" --login $email --user '{"firstName": "'$first'", "lastName": "'$last'", "roles": ["xchange-user","doc-user",'\"${role}\"']}'; done

echo "#### LOOKING FOR ROLES TO CONFIGURE"
for (( i=4; i<=$length; i++))
do 
    awk -v col=$i ' $col >= " " {print $1, $col}' NEW_USERS>> ROLES
done

echo "#### CONFIGURING ROLES"
cat ROLES| while read email role;do sfcc-ci role:grant --login $email --role $role --scope $ENVIRONMENTS; done

echo "#### LISTING NEW USERS CONFIG"
cat NEW_USERS |awk '{print $1}' | while read email;do sfcc-ci user:list -l $email --json|jq -r '.';done

**Comment by walter-foulkes** [comment] 2020-07-29 00:02
thx Tobias

**Comment by sftschaerff** [comment] 2020-07-29 06:50
Hi @walter-foulkes,

I'm glad to hear that the issue could be solved.
Thank you for your input and the script, you've provided.

As the issue is solved, I will close it. All comments and your script will still be accessible from the issue tab.

Regards
Tobias

**Closed by sftschaerff** 2020-07-29 06:50 UTC
